server:
  port: 88
spring:
  application:
    name: mall-gateway
#cloud:
#  gateway:
#    routes:
#      - id: admin_route
#        uri: lb://mall-admin
#        predicates:
#          - Path=/api/**
#        filters:
#          - RewritePath=/api/(?<segment>.*),/mall-admin/$\{segment}