spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.89.118:3306/mall_pms
    hikari:
      max-lifetime: 30000
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.89.118:8848
    alicloud:
      access-key: LTAI4FqsSbxAqQcfKyTfPheU
      secret-key: iGFEJYhfUjtJPXWsWuU3wGmRJ9dCBy
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  application:
    name: mall-product
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000