spring:
  cloud:
    alicloud:
      access-key: your 
      secret-key: your
      oss:
        endpoint: your
        bucket: your
    nacos:
      discovery:
        server-addr: 182.92.89.118:8848
  application:
    name: mall-third-party


server:
  port: 30000
